export let html = [
  "HTML5有哪些新特性?",
  "html5有哪些新特性、移除了哪些元素？",
  "请写出至少5个 html5新增的标签和使用场景",
  "HTML5引入什么新的表单属性",
  "与HTML4相比HTML5废弃了哪些元素",
  "如何处理HTML5新标签的浏览器兼容问题",
  "如何区分HTML和HTML5",
  "HTML5 为什么只需要写 <!DOCTYPE>",
  "HTML5新的doctype和charset是什么？",
  "Doctype作⽤? 严格模式与混杂模式如何区分？它们有何意义?",
  "如何在HTML5页面嵌入音频？",
  "如何在HTML5页面嵌入视频？",
  "HTML5支持哪些新媒体元素？",
  "HTML5的form如何关闭自动完成功能",
  "HTML5 canvas 元素是怎么使用的",
  "Canvas绘制的图形如何保存时加上二维码",
  "Doctype 的作用，严格模式与混杂模式如何区分？",
  "你知道多少种 Doctype 文档类型？",
  "Cookie有哪些弊端",
  "JS操作获取和设置cookie",
  "cookies,sessionStorage,localStorage 的区别",
  "请描述⼀下 cookies ， sessionStorage 和 localStorage 的区别？",
  "浏览器本地存储是怎么样的",
  "HTML5应用缓存和常规的HTML浏览器缓存有何区别",
  "web storage和cookie的区别",
  "HTML5的离线储存的使用和原理",
  "HTML5 的离线储存怎么使⽤，⼯作原理能不能解释⼀下？",
  "浏览器是怎么对 HTML5 的离线储存资源进⾏管理和加载的呢",
  "浏览器是怎么对 HTML5 的离线储存资源进行管理和加载的",
  "什么是 Cookie 隔离？",
  "table 和 div+css 的区别",
  "说你对 HTML 语义化的理解",
  "iframe 的优缺点",
  "iframe有那些缺点？",
  "Label 的作用是什么？是怎么用的？",
  "tite 与 h1 的区别、b 与 strong 的区别、i 与 em 的区别？",
  "举例解释 strong 和 em 标签用法有何不同？",
  "怎么用 CSS 控制块级元素与行内元素以及如何合理使用",
  "行内元素有哪些？块级元素有哪些？ 空 (void) 元素有那些？",
  "列举 HTML 标签中的行内元素，块级元素",
  "如何在页面上实现一个圆形的可点击区域",
  "聊聊 meta 标签",
  "SVG 是什么",
  "Canvas 和 SVG 图形的区别是什么",
  "HTML ‘data-‘属性的作用是什么？",
  "herf 和 src 的区别",
  "锚点的作用是什么？如何设置锚点",
  "页面导入样式时，使用 link 和 @import 有什么区别？",
  "defer 和 async 的区别",
  "网页中 mate viewport 具体参数使用",
  "怎样处理 移动端 1px 被 渲染成 2px 问题？",
  "如何实现浏览器内多个标签页之间的通信？",
  "如何在两个浏览器窗口间通信？",
  "webSocket 如何兼容低版本浏览器",
  "img 中的 alt 和元素的 title 属性作用",
  "浏览器是如何渲染页面的",
  "HTML 和 XHTML 两者有什么区别",
  "xhtml和html有什么区别",
  "html 常见的兼容性问题",
  "实现不使用 border 画出 1px 高的线",
  "介绍一下你对浏览器内核的理解？",
  "WEB 标准是什么",
  "页面可见性（Page Visibility）API 用途",
  "网页验证码是干嘛的，是为了解决什么安全问题",
  "对 WEB 标准以及 W3C 的理解与认识",
  "如何写出高性能的 HTML",
  "CSS 和 JS 的引用放在 HTML 的哪里",
  "⾏内元素有哪些？块级元素有哪些？ 空(void)元素有那些？⾏内元素和块级元素有什么区别？",
  "HTML全局属性(global attribute)有哪些",
  "HTML viewport",
  "meta viewport相关",
  "a：img的alt与title有何异同？b：strong与em的异同？",
  "简述⼀下src与href的区别？",
  "知道的⽹⻚制作会⽤到的图⽚格式有哪些？",
];

export let css = [
  "CSS中定位的方式有哪些?",
  "position的值relative和absolute是相对于谁进行定位的?",
  "absolute 的 containing block 计算方式跟正常流有什么不同?",
  "设置元素浮动后，该元素的display值是多少？",
  "清除浮动的⼏种⽅式，各⾃的优缺点",
  "浮动元素 —— 怎么使用它们、它们有什么问题以及怎么解决这些问题。",
  "position跟display、margin collapse、overflow、float这些特性相互叠加后会怎么样？",
  "display有哪些值？说明他们的作用。",
  "display:none和visibility:hidden的区别？",
  "display、float、position的关系",
  "⾏内元素float left后是否变为块级元素？",
  "display有哪些值？说明他们的作⽤",
  "CSS里的visibility属性有个collapse属性值是干嘛用的？在不同浏览器下以后什么区别？",
  "CSS中link和@import的区别是？",
  "link 与 @import 的区别",
  "CSS3有哪些新特性？",
  "请解释一下CSS3的Flexbox（弹性盒布局模型）,以及适用场景？",
  "CSS3新增伪类有哪些？",
  "before 和 after中双冒号和单冒号 有什么区别？解释一下这2个伪元素的作用。",
  "CSS 的“伪类”和“伪元素”有什么区别？请举例伪元素的几种应用场景。",
  "box-sizing；border-box是怎么回事?",
  "margin的上下左右四个数值？什么原理？",
  "margin和padding分别适合什么场景使用？",
  "CSS旋转属性怎么用？transform 有哪些用法",
  "你对line-height是如何理解的？",
  "css样式（选择器）的优先级",
  "⾃定义字体的使⽤场景",
  "如何美化CheckBox",
  "font-style属性可以让它赋值为“oblique” oblique是什么意思？",
  "CSS哪些属性脱离文档流",
  "div+css的布局较table布局有什么优点？",
  "如何居中div？",
  "请列举 CSS 中用于隐藏元素的两个属性？两者的差异？",
  "三栏布局，中间自适应",
  "元素竖向的百分比设定是相对于容器的高度吗？",
  "什么是响应式设计？响应式设计的基本原理是什么？如何兼容低版本的IE？",
  "一个满屏 品 字布局 如何设计?",
  "⼏种常⻅的CSS布局",
  "CSS ⾃适应布局",
  "有一个高度自适应的div，里面有两个div，一个高度100px，希望另一个填满剩下的高度。",
  "iframe如何实现自适应宽高",
  "写一段CSS让图片（未知大小)水平垂直居中",
  "DICV水平和垂直居中问题，兼容低版本和移动端；",
  "媒体查询 media query 适配布局的用法",
  "如何垂直居中⼀个浮动元素？",
  "CSS 左边定宽，右边⾃适应⽅案",
  "CSS 左右两边定宽，中间⾃适应",
  "CSS 左右居中",
  "CSS 上下垂直居中",
  "CSS 盒模型",
  "display inline-block 什么时候会显示间隙？",
  "CSS选择符有哪些？哪些属性可以继承？优先级算法如何计算？",
  "三角形怎么画",
  "只有一个DIV，怎么实现双大于号那种指针",
  "用纯CSS创建一个三角形的原理是什么？",
  "html5 CSS3画小米logo（注意透明度问题）",
  "如何修改chrome记住密码后自动填充表单的黄色背景?",
  "全屏滚动的原理是什么？用到了CSS的那些属性？",
  "视差滚动效果，如何给每页做不同的动画？",
  "如果需要⼿动写动画，你认为最⼩时间间隔是多久，为什么？",
  "为什么说position absolute 跟float 影响性能？",
  "让一个元素消失可以用什么方法？除了CSS还有其他方法吗？哪个效率高？",
  "JS为什么会放在下面，CSS为什么放在上面",
  "什么是FOUC（无样式内容闪烁）？如何来避免FOUC？",
  "style标签写在body后与body前有什么区别？",
  "CSS优化、提高性能的方法有哪些？",
  "哪些地方会出现CSS阻塞？哪些地方会出现JS阻塞？",
  "在⽹⻚中的应该使⽤奇数还是偶数的字体？为什么呢？",
  "让页面里的字体变清晰，变细用CSS怎么做？",
  "position:fixed;在android下无效怎么处理？",
  "浮动元素引起的问题和解决办法",
  "请解释一下为什么会出现浮动和什么时候需要清除浮动？清除浮动的方式",
  "inline-block边距问题，有4px的边距；怎么解决？",
  "li与li之间有看不见的空白间隔是什么原因引起的？",
  "CSS的浏览器兼容性（谷歌12px和不同浏览器的margin和padding,img下面有空白），原因，解决方法是什么？",
  "常用的CSS hack有哪些？",
  "IE6的兼容问题，如何解决？比如双倍margin",
  "怎么让Chrome支持小于12px 的文字？",
  "overflow scroll时不能平滑滚动的问题怎么处理？",
  "解释下浮动和它的工作原理？",
  "引入样式表CSS的方式有几种？分别是什么？优先级有什么不同",
  "CSS权重优先级是如何计算的？",
  "CSS不同选择器的权重(CSS层叠的规则)",
  "浏览器是怎样解析CSS选择器的？",
  "CSS定义的权重",
  "解释下CSS sprites，以及您要如何在页面或网站中使用它",
  "css sprite是什么,有什么优缺点",
  "为什么要初始化CSS样式？",
  "二级菜单的实现方法",
  "俄罗斯方块的旋转问题",
  "请让页面中的一个元素（10px*10px）围绕坐标(200, 300) 做圆周运动",
  "如果需要手动写动画，你认为最小时间间隔是多久，为什么？",
  "在网页中的应该使用奇数还是偶数的字体？为什么呢？",
  "在 CSS 样式中常使用 px、em 两种长度单位，各有什么优劣，在表现上有什么区别？",
  "使用 CSS 预处理器吗？喜欢那个？",
  "抽离样式模块怎么写，说出思路，有无实践经验？",
  "base64有什么好处，base64有什么缺点？",
  "base64的原理及优缺点",
  "base64 的使⽤",
  "图片格式的问题，png色彩问题",
  "png、jpg、gif 这些图片格式解释一下，分别什么时候用。有没有了解过webp？",
  "PNG\\GIF\\JPG的区别及如何选",
  "CSS的盒子模型有几种？",
  "介绍一下标准的CSS的盒子模型？与低版本IE的盒子模型有什么不同的？IE8以下版本的浏览器中盒子模型有什么不同？",
  "说说盒子模型",
  "对BFC的规范的理解？",
  "对BFC规范(块级格式化上下文：block formatting context)的理解？",
  "如何创建块级格式化上下⽂(block formatting context),BFC有什么⽤",
  "介绍⼀下标准的CSS的盒⼦模型？低版本IE的盒⼦模型有什么不同的？",
  "::before 和 :after中双冒号和单冒号 有什么区别？",
  "CSS合并⽅法",
  "列出你所知道可以改变⻚⾯布局的属性",
  "CSS在性能优化⽅⾯的实践",
  "CSS3动画（简单动画的实现，如旋转等）",
  "stylus/sass/less区别",
  "postcss的作⽤",
  "伪类和伪元素的区别",
  "请⽤CSS写⼀个简单的幻灯⽚效果⻚⾯",
  "什么是外边距重叠？重叠的结果是什么？",
  "rgba()和opacity的透明效果有什么不同？",
  "css中可以让⽂字在垂直和⽔平⽅向上重叠的两个属性是什么？",
  "CSS BFC、IFC、GFC、FF",
];

export let js = [
  "JavaScript 中有几种数据类型",
  "用JavaScript写一个动态的，格式为..年..月..日..时..分..秒的方法",
  "JavaScript 如何让alert弹出框中的信息换行",
  "JavaScript 选项卡的标签栏或者一排单选按钮，如何知道选择是第几个？",
  "利用JavaScript打印出FIbonacci数（不使用全局变量）",
  "JavaScript 实现如下语法的功能 var a=(5).plus(3).minus(6);",
  "JavaScript 实现输出document对象中所有成员的名称和类型",
  "JavaScript 如果利用JS生成一个table?",
  "JavaScript 实现预加载一张图片，加载完成后显示在网页中并设定其高度为50px;宽度为50px;",
  "JavaScript 假设有一个4行td的table,将table里面的td顺序颠倒",
  "JavaScript 模拟一个HashTable类；包含add，remove，contains，length方法",
  "对JavaScript中函数绑定的理解；函数绑定可以使用哪两个函数？函数绑定一般使用在什么情况下？这两个函数的区别是什么？",
  "JavaScript var a=b=c=d=5是什么意思?如果接下来再写一句,d=9,a,b,c的值会变化吗?",
  "var a=b=c=d=[1,2,3,4,5]是什么意思?如果接下来写一句d[5]=9;a,b,c,的值会发生变化吗",
  "JavaScript var a=b=c=d=[1,2,3,4,5]是什么意思?如果接下来再写一句d=[9];a,b,c的值会发生变化吗",
  "JavaScript var n=(1,2,3,4,5),n的值是多少?",
  "JavaScript 如何知道一个变量的数据类型?如何判断数据类型?",
  "JavaScript var str=true+11+null+9+undefined+“zhuanbang”+false+null+9+[],str的值是多少?",
  "JavaScript []和{}表示什么?",
  "JavaScript 语法i++,++i,和+i是什么意思?",
  "JavaScript 什么叫全局变量?什么叫局部变量了?是如何定义出来的?",
  "JavaScript 书写规范/原则",
  "在IE,fireFox,chrome这三个浏览器中,如何查看JS代码的报错?",
  "JavaScript 说一说html代码,css代码和js代码的注释写法?",
  "JavaScript 循环语句有几种写法?用不同的写法写出判断当天是星期几的方法",
  "JavaScript NaN是什么意思?这个值有什么特点?",
  "JavaScript 在switch case判断条件中,用到了break;还有的地方用到了return;请问这两者有何区别?",
  "JavaScript 写一个通用的整数随时学方法,要求有两个参数,用来限定随机数的上限和下限,方法最终能返回这个符合条件的随机数",
  "2022年的春节是2022年02月01日;请写一段代码;算出现在距离春节还有多少天,多少小时,多少分,多少秒",
  "请问alert(Number(“08”));输出的结果是什么?",
  "请使用JavaScript找出name=“A”的内容",
  "JavaScript 下面的目的是把所有的li都删除掉;下面的方法有没有问题?为什么?怎么解决?",
  "JavaScript 作用域闭包的概念,闭包用在哪里有哪些变化?性能如何?",
  "JavaScript 写一个从0到59依次循环的计时器",
  "JavaScript 双十一倒计时更准确",
  "JavaScript null和undefined的区别?",
  "JavaScript add(2, 3, 4)，add(2)(3)(4)和add(2, 3)(4)",
  "JavaScript new操作符具体干了什么呢?",
  "对JSON的了解?",
  "JavaScript document.write 和 innerHTML的区别;",
  "JavaScript call和apply()的作用和区别;",
  "JavaScript 哪些操作会造成内存泄露?",
  "JavaScript 什么是”use strict”?使用它的好处和坏处分别是什么?",
  "JavaScript 如何获取UA",
  "JavaScript eval是做什么的?",
  "JavaScript 对象的深度克隆代码实现",
  "浏览器的严格模式与混杂模式",
  "JavaScript 谈谈 this 对象的理解",
  "JavaScript 什么是window对象? 什么是document对象?",
  "JavaScript tepyof(null)返回什么",
  "JavaScript [“1”, “2”, “3”].map(parseInt) 答案是多少",
  "JavaScript 作用链域",
  "JavaScript 的作用域与变量声明提升",
  "JavaScript 如何判断一个对象是否属于某个类",
  "JavaScript原型，原型链 ? 有什么特点",
  "Javascript中，有一个函数，执行时对象查找时，永远不会去查找原型，这个函数是?",
  "用原生JavaScript的实现过什么功能吗",
  "JavaScript 解释下面这段代码的意思 / 给所有HTML层添加一个高亮的边框",
  "把 Script 标签 放在页面的最底部的body封闭之前 和封闭之后有什么区别？浏览器会如何解析它们？",
  "什么是“前端路由”?什么时候适合使用“前端路由”? “前端路由”有哪些优点和缺点?",
  "知道什么是webkit么? 知道怎么用浏览器的各种工具来调试和debug代码么?",
  "前端开发常用的IE，firefox上的调试工具；分别举例说明用法",
  "JavaScript 如何outerHTML,注意浏览器兼容性",
  "JavaScript (new Date).getTime() 和 +new Date() 都可以取到当前时间戳，它们的实现原 理是什么",
  "JavaScript 查找页面所有类是edit的input，且type是text的元素，遍历他们并返回他们的value",
  "如何使用js把这个div的class的属性改为class_2",
  "请设计一个 JavaScript 函数，该函数接受一个 CSS 属性名作为参数，并返回一个 boolean 值",
  "如何让 input 元素在默认情况下显示“alipay WD Team”，而在光标移入后则显示空白？",
  "JavaScript console(Function instanceof Object); 和这个alert(Object instanceof Function)",
  "JavaScript 请至少写出2种方法，不通过第三个中间变量，交换2个变量的值",
  "JavaScript 你了解 arguments 对象么,它有哪些属性?",
  "JavaScript arguments 是数组么?如果不是请写一段代码将其转化为真正的数组",
  "JavaScript arguments 有什么特性,可以用这些特性做什么?",
  "JavaScript 字符串的常用方法",
  "JavaScript 字符串方法indexOf和lastIndexOf的功能是什么？有什么区别",
  "JavaScript 字符串方法substr和substring的功能是什么？有什么区别",
  "请编写一个JavaScript函数，parseQueryStr，它的用途是把URL参数解析为一个对象",
  "JavaScript String中写一个方法trim，要求能够去除一个字符串开始和结尾的空格",
  "JavaScript 字符串反转",
  "JavaScript 判断一个字符串中出现次数最多的字符；并统计此字符的个数",
  "JavaScript 写一个方法，求字符串中重复的单词",
  "JavaScript 实现千位分隔符方法",
  "JavaScript 写一个字符串转成驼峰的方法，o_div_style_position转成oDivStylePosotion",
  "JavaScript 查找字符串中出现最多字符的个数",
  "JavaScript 去除字符串中连续重复的地方",
  "JavaScript 用js实现千位分隔符?",
  "JavaScript 写一个正则表达式判断字符串是否是对称数",
  "JavaScript 正则验证，当下面的这个表单提交的时候，输入框中不能为空，如果有空格必须把空格去掉，必须是合法的手机号",
  "JavaScript 用正则分解如下超链接",
  "JavaScript 判断字符串由数字和字母组成",
  "解释一下JavaScript的同源策略",
  "JavaScript 为什么要有同源限制",
  "Javascript创建对象的几种方式",
  "用JavaScript实现单利模式的所有实现方式，用说明各种实现方法区别？",
  "JavaScript 继承的实现方法有哪些？分别怎么写？",
  "JavaScript JS如何实现面向对象和继承机制？",
  "JavaScript 模块的封装方法，比如怎样实现私有变量，不能直接赋值，只能通过共有方法访问。",
  "JavaScript 继承的6种方法",
  "JavaScript 如何实现继承？如何避免原型链上面的对象共享？",
  "JavaScript JS 怎么实现一个class(类)",
  "JavaScript 模块化开发怎么做？",
  "JavaScript 的原型，原型链都有什么特点？",
  "JavaScript Ajax读取一个xml文档并进行解析的实例",
  "JavaScript Ajax是什么？ajax的交互模型？",
  "jQuery 如何创建一个Ajax",
  "简述 JavaScript AJAX 的原理",
  "JavaScript AJAX 的优点",
  "JavaScript AJAX 的缺点",
  "JavaScript AJAX 的几种框架",
  "JavaScript AJAX 的过程是怎么样的",
  "JavaScript 简述Ajax异步机制，Ajax有哪些的好处和弊端，介绍下Ajax异步请求的原理和过程",
  "JavaScript XMLHttpRequest是什么、怎样完整地执行一次GET请求、怎样检测错误",
  "JavaScript flash，ajax各自的优缺点。在使用中如何取舍",
  "JavaScript 如何得到HTTP的请求头信息和返回的头信息",
  "JavaScript 页面编码和被请求的资源编码如果不一致如何处理",
  "JavaScript AJAX同步和异步的区别",
  "JavaScript GRT和POET区别？何时使用post？",
  "JavaScript get为什么比post性能好，php/node都用一个东西接收post和get请求，怎么解释get比post性能好",
  "WEB应用从服务器主动推送Data到客户端有哪些方式",
  "JavaScript 跨域怎么实现?如何解决跨域问题",
  "JavaScript jsonP有哪几种方式？",
  "JavaScript 用 a.com 引用了网页 b.com 的js；js是否能读a.com。能够读b.com",
  "AJAX 的状态码有哪些",
  "HTTP状态码有哪些？分别代表什么意思？",
  "http状态吗100,200,300,400,500分别代表什么意思？",
  "聊聊 cache-control",
  "实现一个页面操作不会整页刷新的网站，并且能在浏览器前进、后退时正确响应。给出你的技术实现方案？",
  "JavaScript 使用AJax Post方式向页面check.do发送请求；请求的数据是userID=“admin”，password=“ABC”，假设服务器返回”OK”是成功，客户端踏出”验证通过提示框”",
  "iframe的优缺点",
  "JavaScript 事件冒泡机制",
  "JavaScript 事件兼容性问题有哪些？怎么解决？",
  "JavaScript 写一个通用的事件侦听器函数",
  "JavaScript DOM2级绑定的优点以及兼容性问题",
  "JavaScript 事件IE与火狐的时间机制有什么区别？如何阻止冒泡？",
  "JavaScript 如何使用事件，以及IE和标准DOM事件模型之间存在的差别",
  "我们给一个dom同时绑定两个点击事件，一个用捕获，一个用冒泡，你来说下会执行几次事件，然后会先执行冒泡还是捕获",
  "JavaScript 如何实现事件委托，举例说明",
  "页面上有一个按钮，点击后，在按钮后面插入一个label，内容显示”OK”，已有元素结构",
  "JavaScript DOM创建元素，添加元素，移动元素，复制节点，删除，替换元素，查找节点的方法？",
  "JavaScript innerHTML，innerText，textContent，value、nodeValue属性的区别是什么？",
  "JavaScript 写一个insertBefore和insertAfter方法，并且写出完整测试用例",
  "JavaScript 写出和appendChild向对象的prependChild方法并且写出完整的测试用例",
  "JavaScript 写一个方法，能够实现：获得某元素节点指定标签名的子元素节点，并且写出测试用例",
  "JavaScript setInterval和setTimeout的区别，他们的返回值是什么类型的？表示什么含意呢？",
  "JavaScript DOM中节点有多少类型？元素节点和文本节点的区别？他们有浏览器兼容性问题吗？",
  "JavaScript childNodes和children的区别",
  "JavaScript 中的document.documentElement和document.body的区别",
  "JavaScript documentFragment是什么？它有什么用途，它对浏览器的性能有什么影响",
  "JavaScript 说出常用的数字方法",
  "JavaScript 编写一个；取得指定范围的随机数的方法",
  "JavaScript 常用的时间方法有哪些？",
  "JavaScript 时间类型创建实例时带参数的方式有几种?",
  "JavaScript 说一说Date类中的getTime方法",
  "JavaScript this关键字的表达什么意思?",
  "JavaScript innerText这个属性firefox浏览是不支持的，firefox用什么属性替代innerText这个属性",
  "JavaScript 如何获取网页元素的CSS样式值",
  "JavaScript 点击下面的li，会弹出什么结果?",
  "JavaScript 怎么得到浏览器滚动条的位置?",
  "JavaScript 怎么得到浏览器的高和宽度",
  "JavaScript clientHeight和offsetHeight有什么区别",
  "JavaScript offsetLeft的值和由定位产生的Left属性的值之间，有什么异同",
  "JavaScript 请写一个获取元素相对于屏幕距离的方法",
  "JavaScript 如何获得一个DOM元素的绝对位置?",
  "JavaScript 你封的DOM库什么内容",
  "JavaScript 您的DOM怎么封装的",
  "JavaScript DOM加载过程是怎么样的",
  "JavaScript DOM加载后，运行代码的问题",
  "JavaScript DOM结构,两个节点之间可能存在哪些关系以及如何在节点之间任意移动",
  "JavaScript 请写一个 getParents 方法让它可以获取某一个 DOM 元素的所有父亲节点xx",
  "JavaScript 求数组中的最大值",
  "JavaScript 数组去重",
  "JavaScript 计算出班级的平均分",
  "JavaScript 写出你知道的数组的方法和属性",
  "JavaScript 对象有哪些原生方法，列举一下",
  "JavaScript 数组按照从大到小的顺序排序",
  "JavaScript 请把这个数组里面的数组替换成中文",
  "JavaScript 删除数组中的第m项到第n项，用什么方法",
  "JavaScript 转化一个数字数据为function数组",
  "JavaScript 给Object数组进行排序",
  "JavaScript 在10000下不重复的数字中随机抽取5000不重复样本，多次操作获得的不同结果",
  "JavaScript 1–100000个数字，丢了两个数后打乱顺序怎么找到丢的两个数字？",
  "JavaScript 为数组添加方法indexOf（value），使得下列调用可成功运行",
  "JavaScript 有一个数组，其中保存的都是小写英文字符串，现在要把它按照除了第一个字母外的字符",
  "JavaScript 返回一个合并过的数组",
  "JavaScript 对象的深度克隆",
  "一个页面输入URL到页面加载显示完成，中间发生了什么？",
  "重绘和回流是什么？谈一谈",
  "横向滑动的原理？轮播图的原理",
  "下拉刷新怎么实现?",
  "图片延迟加载的原理，延迟加载的实现原理",
  "JavaScript JS延迟加载的方式有哪些",
  "异步加载的方式有哪些？",
  "异步加载和延迟加载",
  "线程与进程的区",
  "什么叫优雅降级和渐进增强",
  "对网站重构的理解？怎么重构页面？",
  "HTML页面加载和解析流程",
  "浏览器加载和渲染html的顺序",
  "JavaScript 的加载",
];

export let vue = [
  "Vue.js 路由的钩⼦函数",
  "vuex是什么？怎么使⽤？哪种功能场景使⽤它？",
  "Vue.js $route 和 $router 的区别",
  "Vue.js 如何让CSS只在当前组件中起作⽤?",
  "Vue.js keep-alive 的作⽤是什么?",
  "Vue.js 指令v-el的作⽤是什么?",
  "在 Vue.js 中使⽤插件的步骤",
  "Vue.js NextTick 作用",
  "Vue.js 的优点是什么？",
  "Vue.js 路由之间跳转？",
  "Vue.js computed 实现",
  "Vue.js complier 实现",
  "Vue.js 组件中 data 什么时候可以使⽤对象",
  "谈一下你对 Vue.js 的 MVVM 原理的理解",
  "请说一下 Vue.js 响应式数据的原理",
  "Vue.js 的 nextTick的实现原理?",
  "Vue.js 中模板编译原理",
  "简述 Vue.js 中 diff 算法原理",
  "Vue.js 中 v-for 中为什么要用 key",
  "Vue.js 中事件绑定的原理",
  "Vue.js 的v-model实现原理，及如何自定义v-model",
  "Vue.js 中是如何检测数组变化?",
  "为何 Vue.js 采用异步渲染?",
  "Vue.js 中 Computed 的特点",
  "Vue.js Watch中的 deep:true 是如何实现的",
  "Vue.js 何时需要使用 beforeDestroy",
  "Vue.js 中 v-if 和 v-show 的区别",
  "Vue.js中为什么 v-for 和 v-if 不能连用",
  "用 vnode 来描述一个Vue.js DOM结构",
  "Vue.js 中 diff 算法的时间复杂度",
  "Vue.js 中 v-html 会导致哪些问题?",
  "Vue.js 中什么是作用域插槽?",
  "谈谈你对 Vue.js 中 keep-alive 的了解",
  "Vue.js 中实现 hash路由和history路由",
  "Vue.js 的 action 和 mutation 区别",
  "Vue.js 组件的生命周期",
  "描述Vue.js组件渲染和更新过程",
  "Vue.js 组件中的 data 为什么是一个函数?",
  "Vue.js 父子组件生命周期调用顺序",
  "Vue.js 组件如何通信以及有哪些方式?",
  "Vue.js中为什么要使用异步组件？",
  "Vue.js 怎么快速定位哪个组件出现性能问题",
  "Vue-Router 中导航守卫有哪些？",
  "Vue.js ajax 请求放在哪个生命周期中",
  "Vue.js 中相同逻辑如何抽离？",
  "Vue.js 中常见性能优化",
  "Vue3.0 你知道有哪些改进?",
  "说⼀下Vue的双向绑定数据的原理",
  "Vue.js 实现数据双向绑定的原理 Object.defineProperty()",
  "Vue.js 组件间的参数传递",
  "请列举出3个Vue中常⽤的⽣命周期钩⼦函数?",
  "vue-cli ⼯程技术集合介绍",
  "实现 Vue SSR",
  "Vue.js 组件 data 为什么必须是函数",
  "Vue.js extend 能做什么",
  "Vue.js mixin 和 mixins 区别",
  "Vue.js computed 和 watch 区别",
  "Vue.js keep-alive 组件有什么作⽤",
  "Vue.js 响应式原理",
  "Vue.js 数据双向绑定原理,常⻅数据绑定的⽅案",
  "Vue.js VDOM,三个 part",
  "Vue.js 和 react 区别",
];

export let http = [
  "HTTP 协议",
  "HTTP/2 协议",
  "HTTPS 协议",
  "DNS 协议",
  "HTTP的⼏种请求⽅法⽤途",
  "HTTP状态码及其含义",
  "HTTP request报⽂结构是怎样的",
  "HTTP response报⽂结构是怎样的",
  "Ajax原理",
  "ajax 有那些优缺点?",
  "谈一下 WebSocket",
  "ajax、axios、fetch区别",
  "多路复用与多路分解",
  "UDP 协议",
  "TCP 协议",
  "网络层",
  "数据链路层",
  "物理层",
  "Post 和 Get 的区别？",
  "TLS/SSL 中什么一定要用三个随机数，来生成”会话密钥”？",
  "SSL 连接断开后如何恢复？",
  "RSA 算法的安全性保障？",
  "DNS 为什么使用 UDP 协议作为传输层协议？",
  "当你在浏览器中输入 Google.com 并且按下回车之后发生了什么？",
  "谈谈 CDN 服务？",
  "什么是正向代理和反向代理？",
  "负载平衡的两种实现方式？",
  "http 请求方法 options 方法有什么用？",
  "http1.1 和 http1.0 之间有哪些区别？",
  "网站域名加 www 与不加 www 的区别？",
  "即时通讯的实现，短轮询、长轮询、SSE 和 WebSocket 间的区别？",
  "怎么实现多个网站之间共享登录状态",
  "JavaScript Ajax读取一个xml文档并进行解析的实例",
  "JavaScript Ajax是什么？ajax的交互模型？",
  "jQuery 如何创建一个Ajax",
  "简述 JavaScript AJAX 的原理",
  "JavaScript AJAX 的优点",
  "JavaScript AJAX 的缺点",
  "JavaScript AJAX 的几种框架",
  "JavaScript AJAX 的过程是怎么样的",
  "JavaScript 简述Ajax异步机制，Ajax有哪些的好处和弊端，介绍下Ajax异步请求的原理和过程",
  "JavaScript XMLHttpRequest是什么、怎样完整地执行一次GET请求、怎样检测错误",
  "JavaScript flash，ajax各自的优缺点。在使用中如何取舍",
  "JavaScript 如何得到HTTP的请求头信息和返回的头信息",
  "JavaScript 页面编码和被请求的资源编码如果不一致如何处理",
  "JavaScript AJAX同步和异步的区别",
  "JavaScript GRT和POET区别？何时使用post？",
  "JavaScript get为什么比post性能好，php/node都用一个东西接收post和get请求，怎么解释get比post性能好",
  "WEB应用从服务器主动推送Data到客户端有哪些方式",
  "JavaScript 跨域怎么实现?如何解决跨域问题",
  "JavaScript jsonP有哪几种方式？",
  "JavaScript 用 a.com 引用了网页 b.com 的js；js是否能读a.com。能够读b.com",
  "AJAX 的状态码有哪些",
  "HTTP状态码有哪些？分别代表什么意思？",
  "http状态吗100,200,300,400,500分别代表什么意思？",
  "聊聊 cache-control",
  "实现一个页面操作不会整页刷新的网站，并且能在浏览器前进、后退时正确响应。给出你的技术实现方案？",
  "JavaScript 使用AJax Post方式向页面check.do发送请求；请求的数据是userID=“admin”，password=“ABC”，假设服务器返回”OK”是成功，客户端踏出”验证通过提示框”",
  "iframe的优缺点",
];

export let soft = [
  "谈谈你对重构的理解",
  "什么样的前端代码是好的",
  "对前端⼯程师这个职位是怎么样理解的？它的前景会怎么样",
  "你觉得前端⼯程的价值体现在哪",
  "平时如何管理你的项⽬",
  "谈一谈组件封装",
  "前端⼀些常⻅问题",
];

export let webpack = [
  "谈谈你对webpack的看法",
  "webpack 打包体积 优化思路",
  "webpack 打包效率",
  "webpack 编写⼀个loader",
  "说⼀下webpack的⼀些plugin，怎么使⽤webpack对项⽬进⾏优化",
  "webpack 优化打包速度",
  "webpack 如何实现⼀个插件",
  "Webpack 性能优化",
  "实现⼩型Javascript打包⼯具",
];

export let wechat = [
  "微信⼩程序有⼏个⽂件",
  "微信⼩程序怎样跟事件传值",
  "⼩程序的 wxss 和 css 有哪些不⼀样的地⽅？",
  "⼩程序关联微信公众号如何确定⽤户的唯⼀性",
  "微信⼩程序与vue区别",
  "微信⼩程序 登录",
  "微信⼩程序 图⽚导出",
  "微信⼩程序 数据统计",
  "微信⼩程序 ⼯程化",
  "微信⼩程序 架构",
  "微信⼩程序 WXML && WXSS",
  "微信⼩程序的问题",
  "微信⼩程序授权获取⽤户信息流程",
  "微信⼩程序性能优化",
  "微信⼩程序 wepy vs mpvue",
  "微信⼩程序 mpvue",
];

